language: generic
sudo: false
python: 
    - 3.5.4
# cache: apt
# addons:
#     apt:
#         pacakge
cache:
    directories:
        - $HOME/anaconda3
branches:
    only:
        - master
before_install:
    - 
install:
    - bash ./utilities/travis_setup.sh
    - export PATH="$HOME/anaconda3/bin:$PATH"
    - hash -r 
    - source activate asteroid
script:
    # - pytest --cov-config .coveragerc --cov=dynamics --cov=point_cloud --cov=eom_comparison --cov=landing  tests/test_raycaster.py tests/test_attitude.py tests/test_controller.py tests/test_simply.py
    # - travis_wait pytest tests/test_asteroid.py
    - pytest tests/test_attitude.py
    - pytest tests/test_controller.py
    # - pytest tests/test_blender.py code 5 when all are skipped
    # - pytest tests/test_dumbell.py
    - pytest tests/test_eom.py
    - pytest tests/test_lidar.py
    - pytest tests/test_cgal.py
after_success:
    - coveralls

