language: python
sudo: false
python: 
    - 3.5.4
# cache: apt
# addons:
#     apt:
#         pacakge
# cache:
#     directories:
#         - $HOME/anaconda3
branches:
    only:
        - master
before_install:
    - 
install:
    - bash ./utilities/travis_setup.sh
script:
    - pytest -v 
after_success:
    - coveralls

