language: generic
sudo: false
python: 
    - 3.5.4
# cache: apt
# addons:
#     apt:
#         pacakge
cache:
    directories:
        - $HOME/anaconda3
branches:
    only:
        - master
before_install:
    - 
install:
    - bash ./utilities/travis_setup.sh
    - echo ". /home/travis/anaconda3/etc/profile.d/conda.sh" >> ~/.bashrc
    - export PATH="$HOME/anaconda3/bin:$PATH"
    - hash -r 
    - source $HOME/anaconda3/bin/activate
    - conda activate asteroid
script:
    # - pytest --cov-config .coveragerc --cov=dynamics --cov=point_cloud --cov=eom_comparison --cov=landing  tests/test_raycaster.py tests/test_attitude.py tests/test_controller.py tests/test_simply.py
    # - travis_wait pytest tests/test_asteroid.py
    # - pytest --verbose --ignore=tests/test_cgal.py --ignore=tests/test_pcl.py --ignore=tests/test_numba.py --ignore=tests/test_opencv.py
    - pytest --verbose tests/test_distance_to_edges.py
    - pytest --verbose tests/test_distance_to_faces.py
    - pytest --verbose tests/test_distance_to_vertices.py
    - pytest --verbose tests/test_distance_to_mesh.py
after_success:
    - coveralls

