language: python
sudo: false
python: 
    - 3.5.4
# cache: apt
# addons:
#     apt:
#         pacakge
before_install:
    - sudo apt-get -qq update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/anaconda3
    - export PATH="$HOME/anaconda3/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
install:
    # setup the development environment
    #
    - conda create -q -n asteroid --file ./utilities/asteroid_reduced.yml
    - source activate asteroid
script:
    - pytest tests/test_asteroid.py
after_success:
    - coveralls

